services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ilovecoffee

  admin:
    image: adminer
    restart: always
    ports:
      - 9999:8080
